"""
Schémas Pydantic pour la validation des inputs/outputs
"""
from pydantic import BaseModel, Field
from typing import Dict


class PredictionInput(BaseModel):
    """Schéma pour une demande de prédiction de crédit bancaire."""

    age: int = Field(..., ge=18, le=75, description="Âge du client (18-75)")
    monthly_income: float = Field(..., gt=0, description="Revenu mensuel net (MAD)")
    employment_status: int = Field(..., ge=0, le=3, description="Statut emploi: 0=Employé, 1=Indépendant, 2=Retraité, 3=Sans emploi")
    employment_duration: int = Field(..., ge=0, le=40, description="Durée emploi actuel (années)")
    total_debt: float = Field(..., ge=0, description="Total dettes existantes (MAD)")
    loan_amount: float = Field(..., gt=0, description="Montant du prêt demandé (MAD)")
    loan_duration: int = Field(..., ge=12, le=360, description="Durée du prêt (mois)")
    credit_score: int = Field(..., ge=300, le=850, description="Score de crédit (300-850)")
    repayment_history: int = Field(..., ge=0, le=10, description="Historique remboursement (0-10)")
    num_late_payments: int = Field(..., ge=0, le=20, description="Nombre de paiements en retard (2 dernières années)")
    num_open_accounts: int = Field(..., ge=0, le=15, description="Nombre de comptes/lignes de crédit ouverts")
    account_age_years: int = Field(..., ge=0, le=30, description="Ancienneté client (années)")

    class Config:
        json_schema_extra = {
            "example": {
                "age": 35,
                "monthly_income": 5000,
                "employment_status": 0,
                "employment_duration": 5,
                "total_debt": 20000,
                "loan_amount": 80000,
                "loan_duration": 36,
                "credit_score": 700,
                "repayment_history": 7,
                "num_late_payments": 1,
                "num_open_accounts": 3,
                "account_age_years": 5
            }
        }


class PredictionResponse(BaseModel):
    """Schéma pour une réponse de prédiction."""

    statut: str = Field(..., description="Statut (APPROUVÉ ou REJETÉ)")
    prediction: int = Field(..., description="Prédiction (0=Rejeté, 1=Approuvé)")
    confiance_pct: str = Field(..., description="Confiance en pourcentage")
    risque: str = Field(..., description="Niveau de risque")
    data_client: Dict = Field(..., description="Données du client")


class HealthResponse(BaseModel):
    """Schéma pour le health check."""

    status: str = Field(..., description="Status (ok)")
    message: str = Field(..., description="Message")


class ModelInfoResponse(BaseModel):
    """Schéma pour les infos du modèle."""

    type: str = Field(..., description="Type de modèle")
    metrics: Dict = Field(..., description="Métriques")
    is_trained: bool = Field(..., description="Est entraîné")


# ============= CHATBOT SCHEMAS =============

class ChatRequest(BaseModel):
    """Schema for a question asked to the chatbot."""

    # The question text the user types into the chat widget.
    # min_length=1 means Pydantic will automatically reject empty strings
    # (e.g. if someone clicks "send" with nothing typed) before our code even runs.
    question: str = Field(..., min_length=1, description="Question asked by the user")

    class Config:
        # This just shows up in the auto-generated API docs (Swagger UI)
        # as a sample request, so anyone testing the endpoint sees an example.
        json_schema_extra = {
            "example": {
                "question": "What documents do I need for a personal loan?"
            }
        }


class ChatResponse(BaseModel):
    """Schema for the chatbot's response."""

    # The chatbot's generated answer, sent back to the frontend as JSON.
    # FastAPI will automatically wrap this in {"answer": "..."} format.
    answer: str = Field(..., description="Answer generated by the chatbot")